### ISSUE TITLE
System Setup

### ISSUE THREAD

**Issue by sdbale** [Klika-Tech/nucleo-aws-iot-demo#1]
Hi,

Not going to lie I'm new to this and am struggling to get the lambdas and the dashboard to build correctly. I think its all to do with my setup. Would you mind confirming you're OS and node.js versions

Thanks,

Steve

**Comment by mvataleu** [comment]
Hi,

For building lambdas, we use node.js 6.11.0 (LTS: Boron) and npm 3.10.10.
About OS version, for example, I use Fedora Workstation 25 (Linux). But it doesn't matter because node.js installation is cross-platform.

Cheers,

Mikhail

**Comment by singhsaumya25** [comment]
Hi,
I am also new to this and currently I am unable to get the dashboard as it is shown in the demo. I am getting the error which says Network error:503 service unavailable Type Error when attempting to fetch resource. Please help me out with this.

Thanks,
Saumya

**Comment by sdbale** [comment]
Thanks Mikhail. Seems my use of node.js on windows was the primary issue. I have now resolved this by using an EC2 Instance of Fedora.

I do however have what I hope to be one final issue. My dashboard is compiled and deployed, but doesn't get past the loading circle

https://s3-eu-west-1.amazonaws.com/nucleodata/index.html#/dashboard

I wonder if you could point me in the right direction of what to check. I suspect its to do with my API gateway but can't seem to find the problem

Kind Regards, 

Steve

**Comment by singhsaumya25** [comment]
Hi,
Did you find any solution for the dashboard. It happens somehow to me also that I am unable to get the dashboard past the loading circle.
However I am unable to find its cause. Any help in this direction would be appreciated.

Thanks,
Saumya

**Comment by sdbale** [comment]
Using chrome debugger I noticed my API URL was missing a '/ between Prod and getNucleoData. I corrected that, then had to enable CORS on my bucket. Still didn't quite work but I removed security authentication on my API and its now working. I'll re-address security later

**Comment by AsskeJm** [comment]
Hi Steve,

I also have a problem regarding to the dashboard. Everything seems fine in my case, I successfully test my getNucleoData function through api gateway. But there is one thing that when I deployed the dashboard in S3, the bundle.js always got errors like this:

Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at https://s3-ap-southeast-2.amazonaws.com/iotnode/bundle.js:33:9248
    at Array.map (native)
    at https://s3-ap-southeast-2.amazonaws.com/iotnode/bundle.js:33:8991
    at https://s3-ap-southeast-2.amazonaws.com/iotnode/bundle.js:50:4625
    at https://s3-ap-southeast-2.amazonaws.com/iotnode/bundle.js:136:3258
    at Object.dispatch (https://s3-ap-southeast-2.amazonaws.com/iotnode/bundle.js:136:3623)
    at https://s3-ap-southeast-2.amazonaws.com/iotnode/bundle.js:70:22705

Did you see these problems before? Please help my out of this.

Kind Regards,

Leo
